Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081
  config.vm.synced_folder ".", "/vagrant"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2 php
    mkdir /var/www/php/
    curl https://raw.githubusercontent.com/EugeneDruzhynin/devops-hometasks/main/01-vagrant/index.html > /var/www/html/index.html
    curl https://raw.githubusercontent.com/EugeneDruzhynin/devops-hometasks/main/01-vagrant/index.php > /var/www/php/index.php
    echo 'Listen 81' >> /etc/apache2/ports.conf;
    echo '<VirtualHost *:81>\nServerAdmin webmaster@localhost\nDocumentRoot /var/www/php\nErrorLog ${APACHE_LOG_DIR}/error.log\nCustomLog ${APACHE_LOG_DIR}/access.log combined\n</VirtualHost>' >> /etc/apache2/sites-enabled/000-default.conf
    systemctl restart apache2
  SHELL
end
